version: '3.9'
services:
  spyke:
    container_name: spyke
    image: spyke:2.0.0
    build: .
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    dns_search: deb.debian.org
    expose:
      - "53"
      - "67"
      - "80"
      - "443"
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - CAP_NET_RAW
