version: '3.9'
services:
  spyke:
    container_name: spyke
    image: spyke:2.0.0
    build: .
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    dns_search: deb.debian.org
    expose:
      - "53"
      - "67"
      - "80"
      - "443"
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - CAP_NET_RAW
#  server:
#    container_name: server
#    image: server:2.0.0
#    build:
#      context: docker/server
#      dockerfile: Dockerfile.server
#    restart: unless-stopped
#  client:
#    container_name: client
#    image: client:2.0.0
#    build:
#      context: docker/client
#      dockerfile: Dockerfile.client
#    restart: unless-stopped
#    privileged: true
#    depends_on:
#      - "spyke"
#
#networks:
#  dhcp:
#    name: dhcp
#    driver: macvlan
#    driver_opts:
#      dhcp_interface: "wlan0"
#      parent: "wlan0"
#    ipam:
#      config:
#        - subnet: 192.168.8.0/24
#          gateway: 192.168.8.1
